export type OsuSession = {
  osuSessionId: string;
  accountId: string;
  username: string;
  utcOffset: number;
  country: string;
  gameMode: number;
  action: number;
  infoText: string;
  beatmapMd5: string;
  beatmapId: number;
  mods: number;
  spectatorHostOsuSessionId: string | null;
  awayMessage: string | null;
  multiplayerMatchId: number | null;
  lastNpBeatmapId: number | null;
  primary: boolean;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
};
